login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: [POST]

register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: [POST]

subscription_post:
    path: /subscription
    controller: App\Controller\SubscriptionController::createSubscription
    methods: [POST]

subscription_get:
    path: /subscription
    controller: App\Controller\SubscriptionController::getSubscription
    methods: [GET]

subscription_delete:
    path: /subscription
    controller: App\Controller\SubscriptionController::deleteSubscription
    methods: [DELETE]

credit_cards_get:
    path: /credit-cards
    controller: App\Controller\CreditCardController::getCreditCards
    methods: [GET]

subscription_hook:
    path: /subscription-hook
    controller: App\Controller\WebhookController::subscriptionHook
    methods: [POST]